config/routes.rb
Rails.application.routes.draw do
	
  resources :donations

  resources :activity_reports do
    resources :comments, :only => [:new, :edit, :update, :create, :destroy]
  end

  devise_for :users, path_prefix: 'd', controllers: { registrations: "registrations" }
  resources :users do
  member do
  	  get 'image'
  	end	
  end
  
  resources :timereports
  resources :vol_times

  resources :addresses do
    get :autocomplete_catestado_estado, :on => :collection
  end
  
  resources :donors do
    resources :telephones, :addresses, :emails, :comments, :addinfos, :only => [:new, :edit, :update, :create, :destroy]
  end
  
  resources :notes do
  	member do
  	  get 'print'
      get 'image'
  	end
    resources :attachments do
  		member do
  	  	get 'image'
  		end
  	end
  end
  
  resources :attachments do
  	member do
  	  get 'image'
  	end
  end
  
  resources :patients do
    member do
      get 'print'
      get 'notas'
    end
  	resources :addresses, :telephones, :emails, :derechohabientes, :apoyos, :tratamientos, :comments, :diagnosticos, :refclinicas, :houses, :socioecos, :family_members, :addinfos, :only => [:new, :edit, :update, :create, :destroy]
  	
  	resources :attachments do
  		member do
  	  	get 'image'
  		end
  	end 
  
  	
	end

  resources :volunteers do
  	member do
  	  get 'trep'
      get 'image'
  	end
    resources :addresses, :telephones, :emails, :comments, :addinfos, :subprograms, :diagnosticos, :dailyschedules, :only => [:new, :edit, :update, :create, :destroy]
  end

  resources :providers do
    resources :addresses, :telephones, :emails, :comments, :addinfos, :only => [:new, :edit, :update, :create, :destroy]
  end

  resources :contacts do
    resources :addresses, :telephones, :emails, :comments, :addinfos, :only => [:new, :edit, :update, :create, :destroy]
  end
  
  root "pages#home"
  match '/times', :to => "pages#times", via: :get

end

app/models/note.rb
# == Schema Information
#
# Table name: notes
#
#  id         :integer          not null, primary key
#  folio      :integer
#  adeudo     :decimal(22, 2)
#  acuenta    :decimal(22, 2)
#  restan     :decimal(22, 2)
#  subtotal   :decimal(22, 2)
#  total      :decimal(22, 2)
#  fecha      :date
#  patient_id :integer
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class Note < ApplicationRecord
  ransack_allow_all!
  before_save :check_status
  
  belongs_to :patient
  has_many :elements, :dependent => :destroy
  accepts_nested_attributes_for :elements, :allow_destroy => true
  has_many :attachments, :as => :attachable, :dependent => :destroy
  

  validates :patient_id, :presence => true
  validates :folio, :presence => true,:length => { :maximum => 20},
  			:numericality => true, :uniqueness => true
  validates :adeudo, :presence => true, :length => { :maximum => 20}, :numericality => true
  validates :acuenta, :presence => true, :length => { :maximum => 20}, :numericality => true
  validates :restan, :presence => true, :length => { :maximum => 20}, :numericality => true
  validates :subtotal, :presence => true, :length => { :maximum => 20}, :numericality => true
  validates :total, :presence => true, :length => { :maximum => 20}, :numericality => true
  validates :fecha, :presence => true
  
  protected
    def check_status
      @patient = Patient.find(patient_id) 
      if @patient.status != 1
      	errors[:patient_id] << I18n.t('note.error_pat')	
        false
      end
	end  
end

app/controllers/notes_controller.rb
class NotesController < ApplicationController
  load_and_authorize_resource	
  before_action :authenticate_user!
      
  def index
  	@search = Note.ransack(params[:q])
  	@title = t('note.index')
  	@notes = @search.result.order('folio DESC').page(params[:page]).per(10)
  end
  
  def show
    @note = Note.find(params[:id])
    @attachments = @note.attachments
  end
  
  def print 
    @note = Note.find(params[:id])
  	render :layout => false 
  end

  def image
  	@note = Note.find(params[:id])
    send_file "#{Rails.root}#{@note.attachment_url}",:disposition => 'inline', :type=>"application/jpg", :x_sendfile=>true
  end
	
  def new
  	@note = Note.new
  	@note.patient_id = 0
    @folio = notefolio
  	@title = t('helpers.submit.create', :model => Note.to_s)
  	6.times { @note.elements.build }
  	#JSON Data
    @adeudo = getadeudo
    @name = getname
  	respond_to do |format|
  	  format.html
      format.json{ render :json => [@adeudo,@name] }
    end
  end
  
  def edit
    @note = Note.find(params[:id])
    @folio = @note.folio
    @title = t('helpers.submit.update', :model => Note.to_s)
  end
  
  def create
  	@note = Note.create(resource_params)
  	if @note.save
  	  @note = calculos(@note)
  	  if @note.save	
  	    flash[:success] = t('flash.success.create', :model => Note.to_s)
  	    redirect_to @note
  	  else
  	    @title = "New Note"
  	    @folio = notefolio
  	    render 'new'
  	  end
  	else
  	  @title = "New Note"
  	  @folio = notefolio
  	  render 'new'
  	end
  end
  
  def update
    @note = Note.find(params[:id])
    @folio = @note.folio
    if @note.update_attributes(resource_params)
      @note = calculos(@note)
      if @note.save	
        flash[:success] = t('flash.success.edit', :model => Note.to_s)
        redirect_to @note
      else
        @title = t('helpers.submit.create', :model => Note.to_s)
        render 'edit'
      end
    else
      @title = t('helpers.submit.create', :model => Note.to_s)
      render 'edit'
    end
  end
  
  def destroy
    Note.find(params[:id]).destroy
    flash[:success] = t('flash.success.destroy', :model => Note.to_s)
    redirect_to notes_path
  end
  
  private
    # Paramaters that can be changed in the web forms
    def resource_params
      params.require(:note).permit(:folio, :adeudo, :acuenta, :restan, :subtotal,
        :total, :fecha, :patient_id, elements_attributes: [:id, :codigo, :cantidad, :cuota, :descripcion, :_destroy])
    end

    def notefolio
      if Note.last == nil
  	    @folio = 1
  	  else
  	    @folio = Note.last.folio + 1
  	  end	
    end
    
    def getadeudo
      if !params[:id].nil?
  	    Patient.find(params[:id]).notes.last.nil? ? @adeudo = 0 : @adeudo = Patient.find(params[:id]).notes.last.restan
  	  end
    end
    
    def getname
      if !params[:id].nil?
  	    Patient.find(params[:id]).name.nil? ? @name = "" : @name = Patient.find(params[:id]).name
  	  end
    end

	def calculos(note)
	  sub = 0
	  for element in note.elements
	    sub += (element.cuota * element.cantidad)
	  end
	  note.subtotal = sub
	  note.total = note.subtotal + note.adeudo
	  note.restan = note.total - note.acuenta  
	  return note
	end
end

app/helpers/notes_helper.rb
module NotesHelper
end

app/views/notes/_element_fields.html.erb
<tr>
  <td><%= f.text_field :codigo, :size => 5, class: "form-control form-control-sm" %></td>
  <td><%= f.text_field :descripcion, :size => 30, class: "form-control form-control-sm" %></td>
  <td><%= f.text_field :cuota, :size => 3, class: "form-control form-control-sm" %></td>
  <td><%= f.text_field :cantidad, :size => 3, class: "form-control form-control-sm" %></td>
  <td id=<%= "'subtotal_#{index}'" %>></td>	 
  <td><%= f.label :_destroy, t('note.del'), class: "form-label small mb-0" %></td>
  <td><%= f.check_box :_destroy, class: "form-check-input" %></td>
</tr>

app/views/notes/_note.html.erb
<tr>
  <td><%= link_to "#{note.folio}", note, class: "fw-semibold" %></td>
  <td><%= link_to "#{t('patient.cgdvcode')}: #{cgdvcode(note)}", note %></td>
  <td class="text-muted"><%= l note.fecha %></td>
  <% if can? :delete, @note %>
  <td><%= link_to t('helpers.delete.msg'), note, :method => :delete, :confirm => t('helpers.delete.conf'), :title => "#{t('helpers.delete.msg')} #{note.folio}", class: "btn btn-outline-danger btn-sm" %></td>
  <% end %>
  <td><%= link_to t('helpers.print'), print_note_path(note), class: "btn btn-outline-secondary btn-sm" %></td>
</tr>

app/views/notes/_notebody.html.erb
<thead class="table-light">
  <tr>
    <th><%= t('note.codigo') %></th>
    <th><%= t('note.descripcion') %></th>
    <th><%= t('note.cuota') %></th>
    <th><%= t('note.cantidad') %></th>
    <th>Subtotal</th>
  </tr>
</thead>
<tbody>
  <% for element in @note.elements %>
    <tr>
      <td><%= element.codigo %></td>
      <td><%= element.descripcion %></td>
      <td><%= number_to_currency(element.cuota) %></td>
      <td><%= element.cantidad %></td>
      <td><%= number_to_currency(element.cuota*element.cantidad) %></td>
    </tr>
  <% end %>
</tbody>
<tfoot class="table-light">
  <tr>
    <th><%= t('note.subtotal') %></th>
    <th><%= t('note.adeudo') %></th>
    <th><%= t('note.total') %></th>
    <th><%= t('note.acuenta') %></th>
    <th><%= t('note.restan') %></th>
  </tr>
  <tr>
    <td><%= number_to_currency(@note.subtotal) %></td>
    <td><%= number_to_currency(@note.adeudo) %></td>
    <td><%= number_to_currency(@note.total) %></td>
    <td><%= number_to_currency(@note.acuenta) %></td>
    <td><%= number_to_currency(@note.restan) %></td>
  </tr>
</tfoot>

app/views/notes/_notebodyprint.html.erb
<tr align="left" class="noteprint-patient-row">
  <th width="129" align="center" class="noteprint-patient-label"><%= t('patient.name') %>:</th>
  <td width="466" align="center" class="noteprint-patient-value"><%= name(@note) %></td>
  <th width="117" align="center" class="noteprint-patient-label">Registro</th>
  <td width="98" align="center" class="noteprint-patient-value"><%= cgdvcode(@note) %></td>
</tr>
<tr align="center" class="noteprint-columns-row">
  <td><strong><%= t('note.codigo') %></strong></td>
  <td><strong><%= t('note.descripcion') %></strong></td>
  <td><strong><%= t('note.cuota') %></strong></td>
  <td><strong><%= t('note.cantidad') %></strong></td>
</tr>
<% for element in @note.elements %>  
<tr class="noteprint-item-row">
  <td align="center"><%= element.codigo %></td>
  <td align="left"><%= element.descripcion %></td>
  <td align="center"><%= number_to_currency(element.cuota) %></td>
  <td align="center"><%= element.cantidad %></td>
</tr>
<% end %>
<tr align="center" class="noteprint-subtotal-row">
  <th CELLPADDING=10 colspan="3" align="right"><%= t('note.subtotal') %></th>
  <td><%= number_to_currency(@note.subtotal) %></td>
</tr>

app/views/notes/_noteheaderprint.html.erb
<tr class="noteprint-header-row">
  <th align="left" class="nota_title noteprint-brand">Con Ganas de Vivir A.C.</th>
  <th align="right" class="noteprint-meta-label"><%= t('note.fecha') %>: </th>
  <td align="left" class="noteprint-meta-value"><%= l @note.fecha, :format => :long %></td>
  <th align="right" class="nota_title noteprint-meta-label"><%= t('note.folio') %></th>
  <td align="left" class="nota_title noteprint-folio"><u><strong><%= @note.folio %></strong></u></td>
</tr>

app/views/notes/_noteinfo.html.erb
<div class="card border-0 shadow-sm mb-3">
  <div class="card-body p-0">
    <table class="table mb-0 app-table">
      <tbody>
        <tr>
          <td><strong><%= t('patient.cgdvcode') %>:</strong> <%= cgdvcode(@note) %></td>
          <td><strong><%= t('patient.name') %>:</strong> <%= name(@note) %></td>
        </tr>
        <tr>
          <td><strong><%= t('note.folio') %>:</strong> <%= @note.folio %></td>
          <td><strong><%= t('note.fecha') %>:</strong> <%= l @note.fecha, :format => :long %></td>
        </tr>
      </tbody>
    </table>
  </div>
</div>

<div class="card border-0 shadow-sm mb-3">
  <div class="table-responsive">
    <table class="table align-middle mb-0 app-table">
      <%= render 'notebody' %>
    </table>
  </div>
</div>

app/views/notes/_noteprint.html.erb
<table class="nota nota-header" border="0" width="90%">
<%= render 'noteheaderprint' %>
</table>
<table class="noteprint-orgline" border="0" width="100%">
  <tr>
    <td align="left" class="nota_datos">
    Con Ganas de Vivir A.C. RFC: GVI-020604-P61, Av. Universidad 474 Col. Vertiz Narvarte, 
    Benito Juárez México D.F., C.P. 03600 Tels. 5543-1022 y 5543-3192.
    </td>
  </tr>
</table>
<table class="nota nota-body" border="1" width="100%" frame="box" rules="all">
<%= render 'notebodyprint' %>
</table>
<table class="nota nota-totals" border="1" width="100%" frame="box" rules="all">
<%= render 'notetotalsprint' %>
</table>
<table class="nota nota_leyenda nota-legal" border="0" width="100%">
  <tr>
    <td align="left">
    Recibí(mos) los apoyos descritos anteriormente por parte de Con Ganas de Vivir A.C., aceptando
    lo establecido en el reglamento de la Asociación, y reconociendo el monto por concepto de cuota
    de recuperación que aparece en la casilla de total de este documento.
    </td>
  </tr>
</table>

app/views/notes/_notetotalsprint.html.erb
<tr class="noteprint-totals-head">
  <th width="149" align="center"><%= t('note.subtotal') %></th>
  <th width="242" align="center"><%= t('note.adeudo') %></th>
  <th width="242" align="center"><%= t('note.total') %></th>
  <th width="182" align="center"><%= t('note.acuenta') %></th>
  <th width="175" align="center"><%= t('note.restan') %></th>
</tr>
<tr align="center" class="noteprint-totals-values">
  <td><%= number_to_currency(@note.subtotal) %></td>
  <td><%= number_to_currency(@note.adeudo) %></td>
  <td><%= number_to_currency(@note.total) %></td>
  <td><%= number_to_currency(@note.acuenta) %></td>
  <td><%= number_to_currency(@note.restan) %></td>
</tr>
<tr class="noteprint-signature-row">
 <th height="35" align="right">Recibí</th>
 <td height="35" colspan="4"></td>
</tr>

app/views/notes/_patient.html.erb
<div class="card border-0 shadow-sm mb-3 search-panel">
  <div class="card-body">
    <%= search_form_for @search, :url => notas_patient_path(patient), :html => {:method => :get, :class => "row g-3 align-items-end"} do |f| %>
      <div class="col-12">
        <h6 class="text-uppercase text-muted mb-1"><%= t('search.title') %></h6>
      </div>
      <div class="col-12 col-md-6">
        <%= f.label :folio_cont, t('note.folio'), class: "form-label" %>
        <%= f.text_field :folio_eq, class: "form-control" %>
      </div>
      <div class="col-12 col-md-3">
        <%= f.submit t('helpers.search'), class: "btn btn-outline-primary w-100" %>
      </div>
    <% end %>
  </div>
</div>

<div class="d-flex justify-content-between align-items-center mb-2">
  <strong class="text-muted small"><%= t('search.sort') %></strong>
  <div class="pagination-wrap"><%= paginate @notes %></div>
</div>

<div class="card border-0 shadow-sm list-card">
  <div class="table-responsive">
    <table class="table table-hover align-middle mb-0 app-table">
      <thead class="table-light">
        <tr>
          <th><%= sort_link @search, :folio, t('note.folio') %></th>
          <th><%= t('patient.cgdvcode') %></th>
          <th><%= sort_link @search, :created_at, t('all.created_at') %></th>
          <th colspan="2"></th>
        </tr>
      </thead>
      <tbody>
        <%= render @notes %>
      </tbody>
    </table>
  </div>
</div>

<div class="pagination-wrap mt-3"><%= paginate @notes %></div>

app/views/notes/edit.html.erb
<div class="page-toolbar mb-3">
  <h1 class="h2 mb-0"><%= t('helpers.submit.update', :model => Note.to_s) %></h1>
</div>
<div class="alert alert-warning shadow-sm">
  En las notas aparecen los 6 campos por defecto. Si hay campos que no se van a utilizar, para que no se generen errores se debe de seleccionar la opción de <strong>¿Eliminar?</strong>. No los rellenes con '0' o 'xxx'.
</div>
<div class="card border-0 shadow-sm app-form-card">
  <div class="card-body p-3 p-md-4">
    <%= nested_form_for(@note, html: { class: "app-form note-form" }) do |f| %>
      <%= render 'fields', :f => f %>
      <div class="d-flex justify-content-end gap-2 mt-3">
        <%= f.submit t('helpers.edit'), class: "btn btn-primary" %>
      </div>
    <% end %>
  </div>
</div>

app/views/notes/index.html.erb
<div class="page-toolbar mb-3">
  <div class="d-flex flex-column flex-md-row justify-content-between align-items-start align-items-md-center gap-2">
    <h1 class="h2 mb-0"><%= t('note.index') %></h1>
    <%= link_to t('helpers.submit.create', :model => "Nueva Nota"), new_note_path, class: "btn btn-primary btn-sm" %>
  </div>
</div>

<div class="card border-0 shadow-sm mb-3 search-panel">
  <div class="card-body">
    <%= search_form_for @search, :url => notes_path, :html => {:method => :get, :class => "row g-3 align-items-end"} do |f| %>
      <div class="col-12">
        <h6 class="text-uppercase text-muted mb-1"><%= t('search.title') %></h6>
      </div>
      <div class="col-12 col-md-3">
        <%= f.label :folio_eq, t('note.folio'), class: "form-label" %>
        <%= f.text_field :folio_eq, :size => 3, class: "form-control" %>
      </div>
      <div class="col-12 col-md-3">
        <%= f.label :cgdvcode_eq, t('search.cgdvcode'), class: "form-label" %>
        <%= f.text_field :patient_cgdvcode_eq, :size => 3, class: "form-control" %>
      </div>
      <div class="col-12 col-md-4">
        <%= f.label :folio_cont, t('search.name'), class: "form-label" %>
        <%= f.text_field :patient_name_cont, class: "form-control" %>
      </div>
      <div class="col-12 col-md-2">
        <%= f.submit t('helpers.search'), class: "btn btn-outline-primary w-100" %>
      </div>
    <% end %>
  </div>
</div>

<div class="d-flex justify-content-between align-items-center mb-2">
  <strong class="text-muted small"><%= t('search.sort') %></strong>
  <div class="pagination-wrap"><%= paginate @notes %></div>
</div>

<div class="card border-0 shadow-sm list-card">
  <div class="table-responsive">
    <table class="table table-hover align-middle mb-0 app-table">
      <thead class="table-light">
        <tr>
          <th><%= sort_link @search, :folio, t('note.folio'), :default_order => :desc %></th>
          <th><%= t('patient.cgdvcode') %></th>
          <th><%= sort_link @search, :created_at, t('all.created_at'), :default_order => :desc %></th>
          <th colspan="2"></th>
        </tr>
      </thead>
      <tbody>
        <%= render @notes %>
      </tbody>
    </table>
  </div>
</div>

<div class="pagination-wrap mt-3"><%= paginate @notes %></div>

app/views/notes/new.html.erb
<div class="page-toolbar mb-3">
  <h1 class="h2 mb-0"><%= t('helpers.submit.create', :model => Note.to_s) %></h1>
</div>
<div class="alert alert-warning shadow-sm">
  En las notas aparecen los 6 campos por defecto. Si hay campos que no se van a utilizar, para que no se generen errores se debe de seleccionar la opción de <strong>¿Eliminar?</strong>. No los rellenes con '0' o 'xxx'.
</div>
<div class="card border-0 shadow-sm app-form-card">
  <div class="card-body p-3 p-md-4">
    <%= nested_form_for(@note, html: { class: "app-form note-form" }) do |f| %>
      <%= render 'fields', :f => f %>
      <div class="d-flex justify-content-end gap-2 mt-3">
        <%= f.submit t('helpers.create'), :confirm => "¿El Registro CGDV del Paciente es el correcto?", class: "btn btn-primary" %>
      </div>
    <% end %>
  </div>
</div>

app/views/notes/print.html.erb
<!DOCTYPE html>
<html>
  <head>
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta content="text/html; charset=UTF-8" http-equiv="Content-Type" />
    <!--[if lt IE 8]><%= stylesheet_link_tag 'blueprint/ie' %><![endif]-->
    <%= stylesheet_link_tag 'customprint', :media => "screen, print, projection" %>
    <%= csrf_meta_tag %>
  </head>
  <body class="print-preview-body">
    <div id="wrap" class="print-preview-shell note-print-shell">
      <div id="header" align="center" class="print-preview-header">
        <div class="note-print-copy"><%= render 'noteprint' %></div>
        <hr />
        <div class="note-print-copy"><%= render 'noteprint' %></div>
        <hr />
        <div class="note-print-copy"><%= render 'noteprint' %></div>
      </div>
    </div>
  </body>
</html>

app/views/notes/show.html.erb
<div class="page-toolbar mb-3">
  <div class="d-flex flex-column flex-lg-row justify-content-between align-items-start align-items-lg-center gap-2">
    <h1 class="h2 mb-0"><%= t('note.title') %>: <%= @note.folio %></h1>
    <div class="d-flex flex-wrap gap-2">
      <%= link_to t('helpers.submit.update', :model => "Nota"), edit_note_path(@note), class: "btn btn-primary btn-sm" %>
      <%= link_to t('helpers.print'), print_note_path(@note), class: "btn btn-outline-secondary btn-sm" %>
    </div>
  </div>
</div>
<%= render 'noteinfo' %>
<%= render 'attachments/attachments', :model => @note %>