config/routes.rb
Rails.application.routes.draw do
	
  resources :donations

  resources :activity_reports do
    resources :comments, :only => [:new, :edit, :update, :create, :destroy]
  end

  devise_for :users, path_prefix: 'd', controllers: { registrations: "registrations" }
  resources :users do
  member do
  	  get 'image'
  	end	
  end
  
  resources :timereports
  resources :vol_times

  resources :addresses do
    get :autocomplete_catestado_estado, :on => :collection
  end
  
  resources :donors do
    resources :telephones, :addresses, :emails, :comments, :addinfos, :only => [:new, :edit, :update, :create, :destroy]
  end
  
  resources :notes do
  	member do
  	  get 'print'
      get 'image'
  	end
    resources :attachments do
  		member do
  	  	get 'image'
  		end
  	end
  end
  
  resources :attachments do
  	member do
  	  get 'image'
  	end
  end
  
  resources :patients do
    member do
      get 'print'
      get 'notas'
    end
  	resources :addresses, :telephones, :emails, :derechohabientes, :apoyos, :tratamientos, :comments, :diagnosticos, :refclinicas, :houses, :socioecos, :family_members, :addinfos, :only => [:new, :edit, :update, :create, :destroy]
  	
  	resources :attachments do
  		member do
  	  	get 'image'
  		end
  	end 
  
  	
	end

  resources :volunteers do
  	member do
  	  get 'trep'
      get 'image'
  	end
    resources :addresses, :telephones, :emails, :comments, :addinfos, :subprograms, :diagnosticos, :dailyschedules, :only => [:new, :edit, :update, :create, :destroy]
  end

  resources :providers do
    resources :addresses, :telephones, :emails, :comments, :addinfos, :only => [:new, :edit, :update, :create, :destroy]
  end

  resources :contacts do
    resources :addresses, :telephones, :emails, :comments, :addinfos, :only => [:new, :edit, :update, :create, :destroy]
  end
  
  root "pages#home"
  match '/times', :to => "pages#times", via: :get

end

app/models/activity_report.rb
# == Schema Information
#
# Table name: activity_reports
#
#  id           :integer          not null, primary key
#  reporte      :text
#  semana       :integer
#  volunteer_id :integer
#  created_at   :datetime         not null
#  updated_at   :datetime         not null
#

class ActivityReport < ApplicationRecord
  ransack_allow_all!
  belongs_to :volunteer
  
  before_create :set_week
  before_create :get_week

  has_many :comments, as: :commentable, dependent: :destroy

  validates :volunteer_id, presence: true
  #FIXME: Contar que tenga minimo 1 y maximo 750 palabras
  validates :reporte, presence: true, length: { minimum: 1 }
  
  private

  # FIXME: no esta validando
	def get_week
	  week = Time.now.strftime("%W").to_i
	  wday = Time.now.wday
	  week = wday <= 3 ?  week - 1 : week
	  	
	  # registro = ActivityReport.find(:all, :conditions => {:volunteer_id => self.volunteer_id, :semana => week})
	  registro = ActivityReport.where(volunteer_id: self.volunteer_id, semana: week)
	  unless registro.empty?
	    # DEPRECATION WARNING: ActiveModel::Errors#[]= is deprecated and will be removed in Rails 5.1. Use model.errors.add(:semana, ": Ya existe un registro de esta Semana") instead. (called from get_week at /vagrant_data/hadronapp/app/models/activity_report.rb:35)
	    errors[:semana] = ": Ya existe un registro de esta Semana"
	    return false
  	end
	end
	
	def set_week
	  week = Time.now.strftime("%W").to_i
	  wday = Time.now.wday
	  if wday <= 3
	    self.semana = week - 1
	  else
	    self.semana = week
	  end
	end
end

app/controllers/activity_reports_controller.rb
class ActivityReportsController < ApplicationController
  load_and_authorize_resource
  before_action :authenticate_user!	

  def index
  	@activity_reports = []
  	if !current_user.volunteer_id.nil?
  	  if current_user.admin?
  	  	@search = ActivityReport.ransack(params[:q])
  	  	@activity_reports = @search.result.order('semana DESC').page(params[:page]).per(10)
  	  else
  	  	@search = ActivityReport.where(:volunteer_id => current_user.volunteer_id).ransack(params[:q])
  	  	@activity_reports = @search.result.order('semana DESC').page(params[:page]).per(10)
  	  	if @activity_reports.nil?
  	  	  @activity_reports = []
  	  	end
  	  end
  	end
    @title = "Reportes de Actividades"
  end

  def show
    @activity_report = ActivityReport.find(params[:id])
    @comments = @activity_report.comments
  end

  def new
    @activity_report = ActivityReport.new
    @activity_report.volunteer_id = getvolunteerid
    @title = "Reportes de Actividades"
  end

  def create
    @activity_report = ActivityReport.create(resource_params)
    @activity_report.volunteer_id = getvolunteerid
    puts @activity_report
    if @activity_report.save
      flash[:success] = t('flash.success.create', :model => "Reportes de Actividades")
      redirect_to @activity_report
    else
      render :action => 'new'
    end
  end

  def edit
    @activity_report = ActivityReport.find(params[:id])
	@title = "Reportes de Actividades"
  end

  def update
    @activity_report = ActivityReport.find(params[:id])
    if @activity_report.update_attributes(resource_params)
      flash[:success] = t('flash.success.edit', :model => "Reportes de Actividades")
      redirect_to @activity_report
    else
      render :action => 'edit'
    end
  end

  def destroy
    @activity_report = ActivityReport.find(params[:id])
    @activity_report.destroy
    flash[:success] = t('flash.success.destroy', :model => "Reportes de Actividades")
    redirect_to activity_reports_url
  end
  
  private

    def resource_params
      params.require(:activity_report).permit(:reporte, :volunteer_id)
    end
  
    def getvolunteerid
      id = !current_user.volunteer_id.nil? ? current_user.volunteer_id : nil
      return id
    end
end

app/helpers/activity_reports_helper.rb
module ActivityReportsHelper
end

app/views/activity_reports/_activity_report.html.erb
<tr>
  <td><%= link_to activity_report.volunteer.cgdvcode, activity_report.volunteer, class: "fw-semibold" %></td>
  <td><%= link_to "Semana #{activity_report.semana}", activity_report %></td>
  <td><%= link_to l(activity_report.created_at, :format => :rep), activity_report %></td>
  <td><%= link_to truncate(activity_report.reporte, :length => 25), activity_report %></td>
  <td class="smally text-end">
    <div class="d-inline-flex gap-1 flex-wrap justify-content-end">
      <% if can? :edit, ActivityReport %>
        <%= link_to t('helpers.submit.update', :model => "Reporte"), edit_activity_report_path(activity_report), class: "btn btn-outline-primary btn-sm" %>
      <% end %>
      <% if can? :destroy, ActivityReport %>
        <%= link_to t('helpers.delete.msg'), activity_report, :method => :delete, :confirm => t('helpers.delete.conf'), :title => "#{t('helpers.delete.msg')} #{activity_report.created_at}", class: "btn btn-outline-danger btn-sm" %>
      <% end %>
    </div>
  </td>
</tr>

app/views/activity_reports/_fields.html.erb
<%= render 'shared/error_messages', :object => f.object %>
<div class="app-form">
  <div class="mb-3">
    <%= f.label :reporte, class: "form-label" %>
    <%= f.text_area :reporte, class: "form-control" %>
  </div>
</div>

app/views/activity_reports/edit.html.erb
<div class="page-toolbar mb-3">
  <h1 class="h2 mb-0"><%= t('helpers.submit.update', :model => "Reporte de Actividades") %></h1>
</div>
<div class="card border-0 shadow-sm app-form-card">
  <div class="card-body p-3 p-md-4">
    <%= nested_form_for(@activity_report, html: { class: "app-form" }) do |f| %>
      <%= render 'fields', :f => f %>
      <div class="d-flex justify-content-end gap-2 mt-3">
        <%= f.submit t('helpers.edit'), class: "btn btn-primary" %>
      </div>
    <% end %>
  </div>
</div>

app/views/activity_reports/index.html.erb
<div class="page-toolbar mb-3">
  <div class="d-flex flex-column flex-md-row justify-content-between align-items-start align-items-md-center gap-2">
    <h1 class="h2 mb-0">Reportes de Actividades</h1>
    <% unless current_user.volunteer_id.nil? %>
      <%= link_to "Nuevo Reporte de Actividades", new_activity_report_path, class: "btn btn-primary btn-sm" %>
    <% end %>
  </div>
</div>

<div class="card border-0 shadow-sm mb-3 search-panel">
  <div class="card-body">
    <%= search_form_for @search, :url => activity_reports_path, :html => { :method => :get, :class => "row g-3 align-items-end" } do |f| %>
      <div class="col-12">
        <h6 class="text-uppercase text-muted mb-1"><%= t('search.title') %></h6>
      </div>

      <% if current_user.admin? %>
        <div class="col-12 col-md-3">
          <%= f.label :cgdvcode_eq, t('patient.cgdvcode'), class: "form-label" %>
          <%= f.text_field :volunteer_cgdvcode_eq, :size => 3, class: "form-control" %>
        </div>
        <div class="col-12 col-md-5">
          <%= f.label :name_contains, t('patient.name'), class: "form-label" %>
          <%= f.text_field :volunteer_name_eq, class: "form-control" %>
        </div>
      <% end %>

      <div class="col-12 col-md-2">
        <%= f.label :semana_gteq, "Semanas desde:", class: "form-label" %>
        <%= f.text_field :semana_gteq, :size => 3, class: "form-control" %>
      </div>
      <div class="col-12 col-md-2">
        <%= f.label :semana_lteq, "hasta:", class: "form-label" %>
        <%= f.text_field :semana_lteq, :size => 3, class: "form-control" %>
      </div>
      <div class="col-12 col-md-2">
        <%= f.submit t('helpers.search'), class: "btn btn-outline-primary w-100" %>
      </div>
    <% end %>
  </div>
</div>

<div class="d-flex justify-content-between align-items-center mb-2">
  <strong class="text-muted small"><%= t('search.sort') %></strong>
  <div class="pagination-wrap"><%= paginate @activity_reports %></div>
</div>

<div class="card border-0 shadow-sm list-card">
  <div class="table-responsive">
    <table class="table table-hover align-middle mb-0 app-table">
      <thead class="table-light">
        <tr>
          <th><%= sort_link @search, :volunteer_cgdvcode, t('patient.cgdvcode') %></th>
          <th><%= sort_link @search, :semana, "Semanas", :default_order => :desc %></th>
          <th><%= sort_link @search, :created_at, t('all.created_at'), :default_order => :desc %></th>
          <th>Reportes</th>
          <th></th>
        </tr>
      </thead>
      <tbody>
        <%= render @activity_reports %>
      </tbody>
    </table>
  </div>
</div>

<div class="pagination-wrap mt-3"><%= paginate @activity_reports %></div>

app/views/activity_reports/new.html.erb
<div class="page-toolbar mb-3">
  <h1 class="h2 mb-0"><%= t('helpers.submit.create', :model => "Reporte de Actividades") %></h1>
</div>
<div class="card border-0 shadow-sm app-form-card">
  <div class="card-body p-3 p-md-4">
    <%= nested_form_for(@activity_report, html: { class: "app-form" }) do |f| %>
      <%= render 'fields', :f => f %>
      <div class="d-flex justify-content-end gap-2 mt-3">
        <%= f.submit t('helpers.create'), class: "btn btn-primary" %>
      </div>
    <% end %>
  </div>
</div>

app/views/activity_reports/show.html.erb
<div class="page-toolbar mb-3">
  <div class="d-flex flex-column flex-lg-row justify-content-between align-items-start align-items-lg-center gap-2">
    <h1 class="h2 mb-0"><%= "Reporte de la Semana #{@activity_report.semana}" %></h1>
    <div class="d-flex flex-wrap gap-2">
      <% if can? :edit, @activity_report %>
        <%= link_to t('helpers.submit.update', :model => "Reporte"), edit_activity_report_path(@activity_report), class: "btn btn-primary btn-sm" %>
      <% end %>
      <%= link_to "Regresar a Reportes de Actividades", activity_reports_path, class: "btn btn-outline-secondary btn-sm" %>
    </div>
  </div>
</div>

<div class="card border-0 shadow-sm mb-3">
  <div class="card-body p-0">
    <div class="table-responsive">
      <table class="table mb-0 app-table">
        <thead class="table-light">
          <tr>
            <th><%= t('patient.name') %></th>
            <th><%= t('note.fecha') %></th>
          </tr>
        </thead>
        <tbody>
          <tr>
            <td><%= @activity_report.volunteer.name %></td>
            <td><%= l(@activity_report.created_at,:format => :long) %></td>
          </tr>
        </tbody>
      </table>
    </div>
  </div>
</div>

<div class="card border-0 shadow-sm mb-3">
  <div class="card-header"><strong>Reporte</strong></div>
  <div class="card-body">
    <%= simple_format(@activity_report.reporte) %>
  </div>
</div>

<%= render 'comments/comments', :model => @activity_report %>

<div class="mt-3">
  <%= link_to "Regresar a Reportes de Actividades", activity_reports_path, class: "btn btn-outline-secondary btn-sm" %>
</div>