config/routes.rb
Rails.application.routes.draw do
	
  resources :donations

  resources :activity_reports do
    resources :comments, :only => [:new, :edit, :update, :create, :destroy]
  end

  devise_for :users, path_prefix: 'd', controllers: { registrations: "registrations" }
  resources :users do
  member do
  	  get 'image'
  	end	
  end
  
  resources :timereports
  resources :vol_times

  resources :addresses do
    get :autocomplete_catestado_estado, :on => :collection
  end
  
  resources :donors do
    resources :telephones, :addresses, :emails, :comments, :addinfos, :only => [:new, :edit, :update, :create, :destroy]
  end
  
  resources :notes do
  	member do
  	  get 'print'
      get 'image'
  	end
    resources :attachments do
  		member do
  	  	get 'image'
  		end
  	end
  end
  
  resources :attachments do
  	member do
  	  get 'image'
  	end
  end
  
  resources :patients do
    member do
      get 'print'
      get 'notas'
    end
  	resources :addresses, :telephones, :emails, :derechohabientes, :apoyos, :tratamientos, :comments, :diagnosticos, :refclinicas, :houses, :socioecos, :family_members, :addinfos, :only => [:new, :edit, :update, :create, :destroy]
  	
  	resources :attachments do
  		member do
  	  	get 'image'
  		end
  	end 
  
  	
	end

  resources :volunteers do
  	member do
  	  get 'trep'
      get 'image'
  	end
    resources :addresses, :telephones, :emails, :comments, :addinfos, :subprograms, :diagnosticos, :dailyschedules, :only => [:new, :edit, :update, :create, :destroy]
  end

  resources :providers do
    resources :addresses, :telephones, :emails, :comments, :addinfos, :only => [:new, :edit, :update, :create, :destroy]
  end

  resources :contacts do
    resources :addresses, :telephones, :emails, :comments, :addinfos, :only => [:new, :edit, :update, :create, :destroy]
  end
  
  root "pages#home"
  match '/times', :to => "pages#times", via: :get

end

app/models/donation.rb
# == Schema Information
#
# Table name: donations
#
#  id          :integer          not null, primary key
#  folio       :integer
#  donor_id    :integer
#  frecepcion  :date
#  tipo        :integer
#  monto       :string(255)
#  transaccion :string(255)
#  finalidad   :string(255)
#  motivo      :integer
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#

class Donation < ApplicationRecord
  ransack_allow_all!
  belongs_to :donor
  
  validates :donor_id, :presence => true
  validates :folio, :presence => true,:length => { :maximum => 20},
  			:numericality => true, :uniqueness => true
  validates :frecepcion, :presence => true
  validates :tipo, :presence => true
  validates :motivo, :presence => true
  
  TIPO = [['Efectivo',1],['Especie',2],['Transferencia',3],['Tarjeta',4],['Deposito',5],['Paypal',6],['Banxol',7],['Otro',0]]
  MOTIVO = [['Gestion',1],['Espontaneo',2],['En Memoria',3],['Campania',4],['Dedicado',5],['Otro',0]]
end

app/controllers/donations_controller.rb
class DonationsController < ApplicationController
  load_and_authorize_resource	
  before_action :authenticate_user!
  
  def index
  	@search = Donation.ransack(params[:q])
  	@title = t('donation2.index')
  	@donations = @search.result.order('folio DESC').page(params[:page]).per(10)  	
  end

  def show
    @donation = Donation.find(params[:id])
    @title = t('donation2.title')
  end

  def new
    @donation = Donation.new
	@folio = getfolio
  	@title = t('helpers.submit.create', :model => Donation.to_s)
	#JSON Data
    @name = getname
  	respond_to do |format|
  	  format.html
      format.json{ render :json => [@name] }
    end
  end

  def create
    @donation = Donation.create(resource_params)
    if @donation.save
      flash[:success] = t('flash.success.create', :model => Donation.to_s)
      redirect_to @donation
    else
      render :action => 'new'
    end
  end

  def edit
    @donation = Donation.find(params[:id])
    @folio = @donation.folio
    @title = t('helpers.submit.update', :model => Donation.to_s)
  end

  def update
    @donation = Donation.find(params[:id])
    @folio = @donation.folio
    if @donation.update_attributes(resource_params)
      flash[:success] = t('flash.success.edit', :model => Donation.to_s)
      redirect_to @donation
    else
      render :action => 'edit'
    end
  end

  def destroy
    @donation = Donation.find(params[:id])
    @donation.destroy
    flash[:success] = t('flash.success.destroy', :model => Donation.to_s)
    redirect_to donations_url
  end
  
  private
  private
    # Paramaters that can be changed in the web forms
    def resource_params
      params.require(:donation).permit(:folio, :donor_id, :frecepcion, :tipo, :monto, :transaccion, :finalidad, :motivo)
    end

    def getfolio
      if Donation.last == nil
  	    @folio = 1
  	  else
  	    @folio = Donation.last.folio + 1
  	  end	
    end
    
    def getname
      if !params[:id].nil?
  	    Donor.find(params[:id]).name.nil? ? @name = "" : @name = Donor.find(params[:id]).name
  	  end
    end
    
end

app/helpers/donations_helper.rb
module DonationsHelper
end

app/views/donations/_donation.html.erb
<tr>
  <td><%= link_to donation.folio, donation, class: "fw-semibold" %></td>
  <td><%= link_to donation.donor.cgdvcode, donation.donor %></td>
  <td><%= link_to l(donation.frecepcion), donation %></td>
  <td><%= link_to donation.finalidad, donation %></td>
  <td class="text-end">
    <% if can? :destroy, Donation %>
      <%= link_to t('helpers.delete.msg'), donation, :method => :delete, :confirm => t('helpers.delete.conf'), :title => "#{t('helpers.delete.msg')} #{donation.folio}", class: "btn btn-outline-danger btn-sm" %>
    <% end %>
  </td>
</tr>

app/views/donations/_fields.html.erb
<%= render 'shared/error_messages', :object => f.object %>
<div class="row g-3 app-form">
  <div class="col-12 col-md-3">
    <%= f.label :folio, class: "form-label" %>
    <%= f.text_field :folio, :value => @folio, :size => 3, class: "form-control" %>
  </div>
  <div class="col-12 col-md-4">
    <%= f.label :donor_id, class: "form-label" %>
    <%= f.collection_select :donor_id, Donor.order('cgdvcode'), :id, :cgdvcode, {}, class: "form-select" %>
  </div>
  <div class="col-12 col-md-5">
    <%= f.label :donor_id, class: "form-label" %>
    <div id="donor_name" class="form-control bg-light"> </div>
  </div>
  <div class="col-12 col-md-6">
    <%= f.label :frecepcion, class: "form-label d-block" %>
    <div class="date-select-inline">
      <%= f.date_select :frecepcion, { :order => [:day, :month, :year], :start_year => Time.now.year - 10 }, { :class => "form-select d-inline-block w-auto" } %>
    </div>
  </div>
  <div class="col-12 col-md-3">
    <%= f.label :motivo, class: "form-label" %>
    <%= f.select :motivo, Donation::MOTIVO, {}, class: "form-select" %>
  </div>
  <div class="col-12 col-md-3">
    <%= f.label :tipo, class: "form-label" %>
    <%= f.select :tipo, Donation::TIPO, {}, class: "form-select" %>
  </div>
  <div class="col-12 col-md-4">
    <%= f.label :transaccion, class: "form-label" %>
    <%= f.text_field :transaccion, :size => 10, class: "form-control" %>
  </div>
  <div class="col-12 col-md-3">
    <%= f.label :monto, class: "form-label" %>
    <%= f.text_field :monto, :size => 10, class: "form-control" %>
  </div>
  <div class="col-12 col-md-5">
    <%= f.label :finalidad, class: "form-label" %>
    <%= f.text_field :finalidad, :size => 50, class: "form-control" %>
  </div>
</div>

app/views/donations/edit.html.erb
<div class="page-toolbar mb-3">
  <h1 class="h2 mb-0"><%= t('helpers.submit.update', :model => Donation.to_s) %></h1>
</div>
<div class="card border-0 shadow-sm app-form-card">
  <div class="card-body p-3 p-md-4">
    <%= form_for(@donation, html: { class: "app-form" }) do |f| %>
      <%= render 'fields', :f => f %>
      <div class="d-flex justify-content-end gap-2 mt-3">
        <%= f.submit t('helpers.edit'), class: "btn btn-primary" %>
      </div>
    <% end %>
  </div>
</div>

app/views/donations/index.html.erb
<div class="page-toolbar mb-3">
  <div class="d-flex flex-column flex-md-row justify-content-between align-items-start align-items-md-center gap-2">
    <h1 class="h2 mb-0"><%= t('donation2.index') %></h1>
    <%= link_to t('helpers.submit.create', :model => "Nueva Donación"), new_donation_path, class: "btn btn-primary btn-sm" %>
  </div>
</div>

<div class="card border-0 shadow-sm mb-3 search-panel">
  <div class="card-body">
    <%= search_form_for @search, :url => donations_path, :html => {:method => :get, class: "row g-3 align-items-end"} do |f| %>
      <div class="col-12">
        <h6 class="text-uppercase text-muted mb-1"><%= t('search.title') %></h6>
      </div>
      <div class="col-12 col-md-2">
        <%= f.label :folio_cont, t('note.folio'), class: "form-label" %>
        <%= f.text_field :folio_eq, :size => 3, class: "form-control" %>
      </div>
      <div class="col-12 col-md-3">
        <%= f.label :cgdvcode_eq, t('search.cgdvcode'), class: "form-label" %>
        <%= f.text_field :donor_cgdvcode_eq, :size => 3, class: "form-control" %>
      </div>
      <div class="col-12 col-md-5">
        <%= f.label :name_cont, t('search.name'), class: "form-label" %>
        <%= f.text_field :donor_name_cont, class: "form-control" %>
      </div>
      <div class="col-12 col-md-2">
        <%= f.submit t('helpers.search'), class: "btn btn-outline-primary w-100" %>
      </div>
    <% end %>
  </div>
</div>

<div class="d-flex justify-content-between align-items-center mb-2">
  <strong class="text-muted small"><%= t('search.sort') %></strong>
  <div class="pagination-wrap"><%= paginate @donations %></div>
</div>

<div class="card border-0 shadow-sm list-card">
  <div class="table-responsive">
    <table class="table table-hover align-middle mb-0 app-table">
      <thead class="table-light">
        <tr>
          <th><%= sort_link @search, :folio, t('note.folio'), :default_order => :desc %></th>
          <th><%= sort_link @search, :donor_cgdvcode, t('patient.cgdvcode'), :default_order => :desc %></th>
          <th><%= sort_link @search, :frecepcion, t('donation2.frecepcion'), :default_order => :desc  %></th>
          <th>Finalidad</th>
          <th></th>
        </tr>
      </thead>
      <tbody>
        <%= render @donations %>
      </tbody>
    </table>
  </div>
</div>

<div class="pagination-wrap mt-3"><%= paginate @donations %></div>

app/views/donations/new.html.erb
<div class="page-toolbar mb-3">
  <h1 class="h2 mb-0"><%= t('helpers.submit.create', :model => Donation.to_s) %></h1>
</div>
<div class="card border-0 shadow-sm app-form-card">
  <div class="card-body p-3 p-md-4">
    <%= form_for(@donation, html: { class: "app-form" }) do |f| %>
      <%= render 'fields', :f => f %>
      <div class="d-flex justify-content-end gap-2 mt-3">
        <%= f.submit t('helpers.create'), class: "btn btn-primary" %>
      </div>
    <% end %>
  </div>
</div>

app/views/donations/show.html.erb
<div class="page-toolbar mb-3">
  <div class="d-flex flex-column flex-lg-row justify-content-between align-items-start align-items-lg-center gap-2">
    <h1 class="h2 mb-0"><%= t('donation2.title') %>: <%= @donation.folio %></h1>
    <%= link_to t('helpers.submit.update', :model => "Donación"), edit_donation_path(@donation), class: "btn btn-primary btn-sm" %>
  </div>
</div>

<div class="card border-0 shadow-sm">
  <div class="card-body p-0">
    <div class="table-responsive">
      <table class="table mb-0 app-table">
        <tbody>
          <tr>
            <th class="table-light w-25"><%= t('patient.cgdvcode') %></th>
            <td><%= @donation.donor.cgdvcode %></td>
          </tr>
          <tr>
            <th class="table-light"><%= t('patient.name') %></th>
            <td><%= @donation.donor.name %></td>
          </tr>
          <tr>
            <th class="table-light"><%= t('donation2.frecepcion') %></th>
            <td><%= l @donation.frecepcion, :format => :long %></td>
          </tr>
          <tr>
            <th class="table-light">Motivo</th>
            <td><%= donation_motivo(@donation.motivo) %></td>
          </tr>
          <tr>
            <th class="table-light">Tipo</th>
            <td><%= donation_tipo(@donation.tipo) %></td>
          </tr>
          <tr>
            <th class="table-light">Transaccion</th>
            <td><%= @donation.transaccion %></td>
          </tr>
          <tr>
            <th class="table-light">Monto</th>
            <td><%= @donation.monto %></td>
          </tr>
          <tr>
            <th class="table-light">Finalidad</th>
            <td><%= @donation.finalidad %></td>
          </tr>
        </tbody>
      </table>
    </div>
  </div>
</div>