config/routes.rb
Rails.application.routes.draw do
	
  resources :donations

  resources :activity_reports do
    resources :comments, :only => [:new, :edit, :update, :create, :destroy]
  end

  devise_for :users, path_prefix: 'd', controllers: { registrations: "registrations" }
  resources :users do
  member do
  	  get 'image'
  	end	
  end
  
  resources :timereports
  resources :vol_times

  resources :addresses do
    get :autocomplete_catestado_estado, :on => :collection
  end
  
  resources :donors do
    resources :telephones, :addresses, :emails, :comments, :addinfos, :only => [:new, :edit, :update, :create, :destroy]
  end
  
  resources :notes do
  	member do
  	  get 'print'
      get 'image'
  	end
    resources :attachments do
  		member do
  	  	get 'image'
  		end
  	end
  end
  
  resources :attachments do
  	member do
  	  get 'image'
  	end
  end
  
  resources :patients do
    member do
      get 'print'
      get 'notas'
    end
  	resources :addresses, :telephones, :emails, :derechohabientes, :apoyos, :tratamientos, :comments, :diagnosticos, :refclinicas, :houses, :socioecos, :family_members, :addinfos, :only => [:new, :edit, :update, :create, :destroy]
  	
  	resources :attachments do
  		member do
  	  	get 'image'
  		end
  	end 
  
  	
	end

  resources :volunteers do
  	member do
  	  get 'trep'
      get 'image'
  	end
    resources :addresses, :telephones, :emails, :comments, :addinfos, :subprograms, :diagnosticos, :dailyschedules, :only => [:new, :edit, :update, :create, :destroy]
  end

  resources :providers do
    resources :addresses, :telephones, :emails, :comments, :addinfos, :only => [:new, :edit, :update, :create, :destroy]
  end

  resources :contacts do
    resources :addresses, :telephones, :emails, :comments, :addinfos, :only => [:new, :edit, :update, :create, :destroy]
  end
  
  root "pages#home"
  match '/times', :to => "pages#times", via: :get

end

app/models/timereport.rb
# == Schema Information
#
# Table name: timereports
#
#  id           :integer          not null, primary key
#  day          :date
#  begin        :time
#  end          :time
#  volunteer_id :integer
#  created_at   :datetime         not null
#  updated_at   :datetime         not null
#  evento       :string(255)
#

class Timereport < ApplicationRecord
  ransack_allow_all!
  belongs_to :volunteer

  validates :day, :presence => true  
  validates :begin, :presence => true
  validates :end, :presence => true
  validates :volunteer_id, :presence => true
  
  DAYS = [['Lunes',1],['Martes',2],['Miercoles',3],['Jueves',4],['Viernes',5],['Sabado',6],['Domingo',7]]
  EVENTO = ['Eventos Especiales', 'Apoyo Intrahospitalario', 'Suenos y Deseos', 'Captacion de Fondos', 'Apoyo en Labores Administrativas', 'Grupos de Autoayuda','Sobrevivientes', 'Fugarte', 'Dia de Reyes', 'Dia del Nin@', 'Corriendo por la Vida', 'Donador de sangre y o plaquetas', 'Curso de Capacitacion Basico', 'Curso de Capacitacion A', 'Curso de Capacitacion B', 'Curso de Capacitacion C', 'Curso de Capacitacion D', 'Curso de Capacitacion Tematico', 'Otr@s']

    def tiempo
      total = self.end - self.begin
      hrs = (total/3600).to_i
  	  mins = (total/60 - hrs * 60).to_i
  	  return "#{hrs} hrs, #{mins} mins"
    end
    
    def tiempo_num
      total = self.end - self.begin
      hrs = (total/3600).to_i
  	  mins = (total/60 - hrs * 60)/100.to_i
  	  return [hrs,mins]
    end 
  
end

app/controllers/timereports_controller.rb
class TimereportsController < ApplicationController
  load_and_authorize_resource
  before_action :authenticate_user!
  
  def index
  	@search = Timereport.ransack(params[:q])
  	@title = t('header.timereport')
  	@timereports = @search.result.order('created_at DESC').page(params[:page]).per(15)
  end
  
  def show
    @timereport = Timereport.find(params[:id])
  end
	
  def new
  	@timereport = Timereport.new
  	@title = t('helpers.submit.create', :model => 'timereports.title')
  end
  
  def edit
    @timereport = Timereport.find(params[:id])
    @title = t('helpers.submit.update', :model => 'timereports.title')
  end
  
  def create
  	@timereport = Timereport.create(resource_params)
  	if @timereport.save	
  	  flash[:success] = t('flash.success.create', :model => 'timereports.title')
  	  redirect_to @timereport
  	else
  	  @title = t('helpers.submit.create', :model => 'timereports.title')
  	  render 'new'
  	end
  end
  
  def update
    @timereport = Timereport.find(params[:id])
    if @timereport.update_attributes(resource_params)	
      flash[:success] = t('flash.success.edit', :model => 'timereports.title')
      redirect_to @timereport
    else
      @title = t('helpers.submit.create', :model => 'timereports.title')
      render 'edit'
    end
  end
  
  def destroy
    Timereport.find(params[:id]).destroy
    flash[:success] = t('flash.success.destroy', :model => 'timereports.title')
    redirect_to timereports_path
  end

  private
    # Paramaters that can be changed in the web forms
    def resource_params
      params.require(:timereport).permit(:day, :begin, :end, :evento, :volunteer_id)
    end
end

app/helpers/timereports_helper.rb
module TimereportsHelper
end

app/views/timereports/_fields.html.erb
<%= render 'shared/error_messages', :object => f.object %>
<div class="row g-3 app-form">
  <div class="col-12 col-lg-6">
    <%= f.label :evento, t('volunteer.evento'), class: "form-label" %>
    <%= f.select :evento, Timereport::EVENTO, {}, class: "form-select" %>
  </div>

  <div class="col-12 col-md-4 col-lg-3">
    <%= f.label :volunteer_id, t('patient.cgdvcode'), class: "form-label" %>
    <%= f.collection_select :volunteer_id, Volunteer.order('cgdvcode'), :id, :cgdvcode, {}, class: "form-select" %>
  </div>

  <div class="col-12 col-md-8 col-lg-3">
    <%= f.label :volunteer_id, t('patient.name'), class: "form-label" %>
    <div id="volunteer_name" class="form-control bg-light"> </div>
  </div>

  <div class="col-12 col-lg-4">
    <%= f.label :day, t('volunteer.day'), class: "form-label d-block" %>
    <div class="date-select-inline">
      <%= f.date_select :day, {}, { class: "form-select d-inline-block w-auto" } %>
    </div>
  </div>

  <div class="col-12 col-md-6 col-lg-4">
    <%= f.label :begin, t('volunteer.begin'), class: "form-label d-block" %>
    <div class="date-select-inline">
      <%= f.time_select :begin, {}, { class: "form-select d-inline-block w-auto" } %>
    </div>
  </div>

  <div class="col-12 col-md-6 col-lg-4">
    <%= f.label :end, t('volunteer.end'), class: "form-label d-block" %>
    <div class="date-select-inline">
      <%= f.time_select :end, {}, { class: "form-select d-inline-block w-auto" } %>
    </div>
  </div>
</div>

app/views/timereports/_timereport.html.erb
<tr>
  <% if can? :read, Volunteer %>
  <td><%= link_to cgdvcode_vol(timereport), volunteer_path(timereport.volunteer_id), class: "fw-semibold" %></td>
  <% end %>
  <td><%= link_to l(timereport.day), timereport %></td>
  <td><%= link_to l(timereport.begin, :format => :hourmin), timereport %></td>
  <td><%= link_to l(timereport.end, :format => :hourmin), timereport %></td>
  <td><%= link_to timereport.tiempo, timereport %></td>
  <td><%= link_to timereport.evento, timereport %></td>
  <td class="smally text-end">
    <div class="d-inline-flex gap-1 flex-wrap justify-content-end">
      <% if can? :edit, timereport %>
        <%= link_to t('helpers.edit'), edit_timereport_path(timereport), class: "btn btn-outline-primary btn-sm" %>
      <% end %>
      <% if can? :destroy, timereport %>
        <%= link_to t('helpers.delete.msg'), timereport_path(timereport), :method => :delete, :confirm => t('helpers.delete.conf'), :title => "#{t('helpers.delete.msg')} #{timereport.begin}", class: "btn btn-outline-danger btn-sm" %>
      <% end %>
    </div>
  </td>
</tr>

app/views/timereports/_volunteer.html.erb
<%= render @timereports %>

app/views/timereports/edit.html.erb
<div class="page-toolbar mb-3">
  <div class="d-flex flex-column flex-lg-row justify-content-between align-items-start align-items-lg-center gap-2">
    <h1 class="h2 mb-0"><%= t('helpers.submit.update', :model => Timereport.to_s) %></h1>
    <div class="d-flex flex-wrap gap-2">
      <% if can? :read, VolTime %>
        <%= link_to "Añadir/Acumular Tiempo", vol_times_path, class: "btn btn-outline-secondary btn-sm" %>
      <% end %>
      <%= link_to "Reportar/Restar Tiempo", timereports_path, class: "btn btn-secondary btn-sm" %>
    </div>
  </div>
</div>
<div class="card border-0 shadow-sm app-form-card">
  <div class="card-body p-3 p-md-4">
    <%= nested_form_for(@timereport, html: { class: "app-form" }) do |f| %>
      <%= render 'fields', :f => f %>
      <div class="d-flex justify-content-end gap-2 mt-3">
        <%= f.submit t('helpers.edit'), class: "btn btn-primary" %>
      </div>
    <% end %>
  </div>
</div>

app/views/timereports/index.html.erb
<div class="page-toolbar mb-3">
  <div class="d-flex flex-column flex-lg-row justify-content-between align-items-start align-items-lg-center gap-2">
    <h1 class="h2 mb-0"><%= t('timereport.title') %></h1>
    <div class="d-flex flex-wrap gap-2">
      <% if can? :read, VolTime %>
        <%= link_to "Añadir/Acumular Tiempo", vol_times_path, class: "btn btn-outline-secondary btn-sm" %>
      <% end %>
      <% if can? :read, Timereport %>
        <%= link_to "Reportar/Restar Tiempo", timereports_path, class: "btn btn-secondary btn-sm" %>
      <% end %>
      <%= link_to t('helpers.submit.create', :model => "Nuevo Reporte de Tiempo"), new_timereport_path, class: "btn btn-primary btn-sm" %>
    </div>
  </div>
</div>

<div class="card border-0 shadow-sm mb-3 search-panel">
  <div class="card-body">
    <%= search_form_for @search, :url => timereports_path, :html => { :method => :get, :class => "row g-3 align-items-end" } do |f| %>
      <div class="col-12">
        <h6 class="text-uppercase text-muted mb-1"><%= t('search.title') %></h6>
      </div>
      <div class="col-12 col-md-2">
        <%= f.label :cgdvcode_eq, t('search.cgdvcode'), class: "form-label" %>
        <%= f.text_field :volunteer_cgdvcode_eq, :size => 3, class: "form-control" %>
      </div>
      <div class="col-12 col-md-4">
        <%= f.label :evento_cont, t('volunteer.evento'), class: "form-label" %>
        <%= f.text_field :evento_cont, class: "form-control" %>
      </div>
      <div class="col-12 col-md-4">
        <%= f.label :name_cont, t('patient.name'), class: "form-label" %>
        <%= f.text_field :volunteer_name_cont, class: "form-control" %>
      </div>
      <div class="col-12 col-lg-6">
        <%= f.label :day_gteq, "Desde: ", class: "form-label d-block" %>
        <div class="date-select-inline">
          <%= f.date_select :day_gteq, { :default => 1.year.ago, :start_year => Time.now.year - 20, :end_year => Time.now.year }, { :class => "form-select d-inline-block w-auto" } %>
        </div>
      </div>
      <div class="col-12 col-lg-4">
        <%= f.label :day_lteq, "Hasta: ", class: "form-label d-block" %>
        <div class="date-select-inline">
          <%= f.date_select :day_lteq, { :start_year => Time.now.year - 20, :end_year => Time.now.year }, { :class => "form-select d-inline-block w-auto" } %>
        </div>
      </div>
      <div class="col-12 col-lg-2">
        <%= f.submit t('helpers.search'), class: "btn btn-outline-primary w-100" %>
      </div>
    <% end %>
  </div>
</div>

<div class="d-flex justify-content-between align-items-center mb-2">
  <strong class="text-muted small"><%= t('search.sort') %></strong>
  <div class="pagination-wrap"><%= paginate @timereports %></div>
</div>

<div class="card border-0 shadow-sm list-card">
  <div class="table-responsive">
    <table class="table table-hover align-middle mb-0 app-table">
      <thead class="table-light">
        <tr>
          <th><%= sort_link @search, :volunteer_cgdvcode, t('patient.cgdvcode'), :default_order => :desc %></th>
          <th><%= sort_link @search, :day, t('volunteer.day'), :default_order => :desc %></th>
          <th><%= sort_link @search, :begin, t('volunteer.begin'), :default_order => :desc %></th>
          <th><%= sort_link @search, :end, t('volunteer.end'), :default_order => :desc %></th>
          <th><%= t('volunteer.tiempo') %></th>
          <th><%= sort_link @search, :evento, t('volunteer.evento') %></th>
          <th></th>
        </tr>
      </thead>
      <tbody>
        <%= render @timereports %>
      </tbody>
      <tfoot class="table-light">
        <tr>
          <td colspan="3"></td>
          <th>Tiempo Total:</th>
          <th><%= tiempo_total(@timereports) %></th>
          <td colspan="2"></td>
        </tr>
      </tfoot>
    </table>
  </div>
</div>

<div class="pagination-wrap mt-3"><%= paginate @timereports %></div>

app/views/timereports/new.html.erb
<div class="page-toolbar mb-3">
  <div class="d-flex flex-column flex-lg-row justify-content-between align-items-start align-items-lg-center gap-2">
    <h1 class="h2 mb-0"><%= t('helpers.submit.create', :model => Timereport.to_s) %></h1>
    <div class="d-flex flex-wrap gap-2">
      <% if can? :read, VolTime %>
        <%= link_to "Añadir/Acumular Tiempo", vol_times_path, class: "btn btn-outline-secondary btn-sm" %>
      <% end %>
      <%= link_to "Reportar/Restar Tiempo", timereports_path, class: "btn btn-secondary btn-sm" %>
    </div>
  </div>
</div>
<div class="card border-0 shadow-sm app-form-card">
  <div class="card-body p-3 p-md-4">
    <%= nested_form_for(@timereport, html: { class: "app-form" }) do |f| %>
      <%= render 'fields', :f => f %>
      <div class="d-flex justify-content-end gap-2 mt-3">
        <%= f.submit t('helpers.create'), class: "btn btn-primary" %>
      </div>
    <% end %>
  </div>
</div>

app/views/timereports/show.html.erb
<div class="page-toolbar mb-3">
  <div class="d-flex flex-column flex-lg-row justify-content-between align-items-start align-items-lg-center gap-2">
    <h1 class="h2 mb-0"><%= name_vol(@timereport) %>: <%= l @timereport.day %></h1>
    <div class="d-flex flex-wrap gap-2">
      <%= link_to t('helpers.submit.update', :model => "Reporte de Tiempo"), edit_timereport_path(@timereport), class: "btn btn-primary btn-sm" %>
      <% if can? :read, Timereport %>
        <%= link_to "Regresar a Reportar/Restar Tiempo", timereports_path, class: "btn btn-outline-secondary btn-sm" %>
      <% end %>
    </div>
  </div>
</div>

<div class="card border-0 shadow-sm">
  <div class="card-body p-0">
    <div class="table-responsive">
      <table class="table mb-0 app-table">
        <tbody>
          <tr><th class="table-light w-25"><%= t('patient.cgdvcode') %></th><td><%= cgdvcode_vol(@timereport) %></td></tr>
          <tr><th class="table-light"><%= t('volunteer.evento') %></th><td><%= @timereport.evento %></td></tr>
          <tr><th class="table-light"><%= t('volunteer.day') %></th><td><%= l @timereport.day %></td></tr>
          <tr><th class="table-light"><%= t('volunteer.begin') %></th><td><%= l @timereport.begin, :format => :hourmin %></td></tr>
          <tr><th class="table-light"><%= t('volunteer.end') %></th><td><%= l @timereport.end, :format => :hourmin %></td></tr>
          <tr><th class="table-light"><%= t('volunteer.tiempo') %></th><td><%= @timereport.tiempo %></td></tr>
        </tbody>
      </table>
    </div>
  </div>
</div>